name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Sync deps
        run: uv sync --all-extras --dev

      - name: Lint & Type-check
        run: |
          uv run ruff check .
          uv run ruff format --check .
          uv run mypy langchain_superlinked

      - name: Unit tests
        run: uv run pytest --disable-socket --allow-unix-socket tests/unit_tests

      - name: Integration tests (standard)
        run: |
          uv run pytest tests/integration_tests || code=$?; \
          if [ "$code" != "5" ] && [ -n "$code" ]; then exit $code; fi

      - name: Smoke test
        run: uv run python scripts/smoke_test.py

      - name: Build sdist and wheel
        run: uv run python -m build
